### ISSUE TITLE
Suggestion: Add usage section to readme

### ISSUE THREAD

**Issue by jonasstein** [fosnola/libstaroffice#3]
I could not see if this is a plugin for libreoffice, vim, kde office or a command line application in our package description on gentoo https://packages.gentoo.org/packages/app-text/libstaroffice
But I see it is not so clear from the upstream readme either.
Best, JS

**Comment by fosnola** [comment]
Hello Jonas,
I have added a small subsection _How to use as an end-user_ in https://github.com/fosnola/libstaroffice/wiki. 

Let me know if this is sufficient or not...

**Comment by jonasstein** [comment]
perfect. Thank you!
