### ISSUE TITLE
hi, does this lib for extracting MS office format files?

### ISSUE THREAD

**Issue by wuyang-dl** [fosnola/libstaroffice#9]
I tried to complie libreoffice, and find how libreoffice extracts MS files.
but it is hard to compile, I give up.

libreoffice use libstaroffice lib, I want to know whether is this lib extracting MS office format?

ths

**Comment by fosnola** [comment]
Hello,
no, this filter tries only to import StarOffice binary files...

I do not know what you mean by "MS office format", ie. almost each version of Microsoft Office writes text, spreadsheet, ... documents using a different format. In LibreOffice, the newest formats are imported directly in the LibreOffice's code(°), while some very old formats can be imported via some external libraries (for instance, libmwaw can import some very old Mac Word and PowerPoint files while libwps can import some old Pc Word documents).

(°) filter/Configuration_filter.mk contains the list of LibreOffice's filters ( whose _descriptions_ can be found in source/config/fragments/filters/* and source/config/fragments/types/* ), ... ; then if you look for the strings which matches the _prop oor:name="Type"_ 's value, you may be able to find the corresponding sources' code. For instance, if I do not make mistake, sw/source/filter/ww8 is used to import MSWord 97-2007 file.

**Comment by wuyang-dl** [comment]
thank you, i will have a deep look at thesr code.

**Comment by wuyang-dl** [comment]
hi，I studied these xml. and tried to locate correspondent code to extract these office format. e.g. grep grep -r -i "*doc*" ./  

and find poppler(a third part lib to handle with pdf ),  but failed to find code to handle office format.

can you tell me where are these code. thanks!

**Comment by wuyang-dl** [comment]
or can you recommend me another 3rd lib(open source) which can extract office file. (C or C++ code)

I know there are soma C# and java libs for extracting office file, but they are not suitable for me.

thanks!

**Comment by fosnola** [comment]
Ok, it is better to search for the FilterService name, for instance, If you want to find the sources of the importer of the docx file
```
grep FilterServ filter/source/config/fragments/filters/MS_Word_2007_XML.xcu
        <prop oor:name="FilterService"><value>com.sun.star.comp.Writer.WriterFilter</value></prop>
```
now searching for com.sun.star.comp.Writer.WriterFilter in sw (sw contains the main writer source of LibreOffice) gives :
```
grep -r com.sun.star.comp.Writer.WriterFilter sw/source/
sw/source//filter/xml/xmlimp.cxx:    uno::Reference<document::XFilter> xFilter(xMultiServiceFactory-createInstance("com.sun.star.comp.Writer.WriterFilter"), uno::UNO_QUERY_THROW);
sw/source//filter/docx/swdocxreader.cxx:    uno::Reference<uno::XInterface> xInterface(xMultiServiceFactory-createInstance("com.sun.star.comp.Writer.WriterFilter"), uno::UNO_SET_THROW);
sw/source//filter/docx/swdocxreader.cxx:                xMultiServiceFactory->createInstance( "com.sun.star.comp.Writer.WriterFilter" ),
```
The first file seems to give a good starting point.

> or can you recommend me another 3rd lib(open source) which can extract office file. (C or C++ code)

To my knowledge, all big applications created their own filters for the recent MSOffice formats. And as these formats are very complex, if there want to convert them reasonably well, their codes will probably be very long and very difficult to read (as there may call many other internal functions to create some frames/tables/... )
